---
name: Debian 10
on:
  push:
    branches-ignore: [main]
    paths:
      - ".github/workflows/debian-10.yml"
      - "debian/10"
  pull_request:
    branches: [develop, main]
    paths:
      - ".github/workflows/debian-10.yml"
      - "debian/10"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Docker Build
        run: |
          cd debian/10
          docker build -t debian:10 .
