---
name: Ubuntu 18.04
on:
  push:
    branches-ignore: [main]
    paths:
      - ".github/workflows/ubuntu-1804.yml"
      - "ubuntu/18.04"
  pull_request:
    branches: [develop, main]
    paths:
      - ".github/workflows/ubuntu-1804.yml"
      - "ubuntu/18.04"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Docker Build
        run: |
          cd ubuntu/18.04
          docker build -t ubuntu:18.04 .
