---
name: Ubuntu 20.04
on:
  push:
    branches-ignore: [main]
    paths:
      - ".github/workflows/ubuntu-2004.yml"
      - "ubuntu/20.04/**"
  pull_request:
    branches: [develop, main]
    paths:
      - ".github/workflows/ubuntu-2004.yml"
      - "ubuntu/20.04/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ubuntu/20.04
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
          tags: mrlesmithjr/ubuntu:20.04
